---
- hosts: all
  become: yes

  tasks:

    - name: install EPEL release package
      yum:
        name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
        state: present
      when: ansible_os_family == 'RedHat'

    - name: install IUS release package
      yum:
        name: "https://repo.ius.io/ius-release-el{{ ansible_distribution_major_version }}.rpm"
        state: present
      when: ansible_os_family == 'RedHat'
